# Prepare dataset

## Load data from Kaggle

In [1]:
from google.colab import userdata
import os

# ดึงข้อมูลจาก secret
os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

In [2]:
# Dowload Online Sales dataset
!kaggle datasets download -d samruddhi4040/online-sales-data

Dataset URL: https://www.kaggle.com/datasets/samruddhi4040/online-sales-data
License(s): CC0-1.0
Downloading online-sales-data.zip to /content
  0% 0.00/18.9k [00:00<?, ?B/s]
100% 18.9k/18.9k [00:00<00:00, 66.1MB/s]

In [3]:
# Dowload curency conversion rate
!kaggle datasets download -d meetnagadia/us-dollar-inr-rupee-dataset20032021

Dataset URL: https://www.kaggle.com/datasets/meetnagadia/us-dollar-inr-rupee-dataset20032021
License(s): ODbL-1.0
Downloading us-dollar-inr-rupee-dataset20032021.zip to /content
  0% 0.00/68.2k [00:00<?, ?B/s]
100% 68.2k/68.2k [00:00<00:00, 40.9MB/s]

Unzip file

In [4]:
!unzip -q online-sales-data.zip

In [5]:
!unzip -q us-dollar-inr-rupee-dataset20032021.zip

## Read the data with pandas

### Transactions table

In [6]:
import pandas as pd
transactions_df = pd.read_csv('Details.csv')
transactions_df.head(10)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
5,B-25881,2244,247,4,Clothing,Trousers,Credit Card
6,B-25696,275,-275,4,Clothing,Saree,COD
7,B-25687,387,-213,5,Clothing,Saree,UPI
8,B-25643,50,-44,2,Clothing,Hankerchief,UPI
9,B-25851,135,-54,5,Clothing,Kurti,COD

In [7]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

### Customers table

In [8]:
customer_df = pd.read_csv('Orders.csv')
customer_df.head(10)

  Order ID  Order Date CustomerName           State       City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh    Mathura
1  B-25993  03-02-2018       Madhav           Delhi      Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh    Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra     Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh     Indore
5  B-25967  21-01-2018       Sudevi   Uttar Pradesh  Prayagraj
6  B-25955  16-01-2018        Shiva     Maharashtra       Pune
7  B-26093  27-03-2018       Sarita     Maharashtra       Pune
8  B-25798  01-10-2018       Shishu  Andhra Pradesh  Hyderabad
9  B-25602  01-04-2018       Vrinda     Maharashtra       Pune

In [9]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    object
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

In [10]:
customer_df['Order Date'] = pd.to_datetime(customer_df['Order Date'], format='%d-%m-%Y')
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    datetime64[ns]
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 19.7+ KB

In [11]:
customer_df.head(10)

  Order ID Order Date CustomerName           State       City
0  B-26055 2018-03-10    Harivansh   Uttar Pradesh    Mathura
1  B-25993 2018-02-03       Madhav           Delhi      Delhi
2  B-25973 2018-01-24  Madan Mohan   Uttar Pradesh    Mathura
3  B-25923 2018-12-27        Gopal     Maharashtra     Mumbai
4  B-25757 2018-08-21     Vishakha  Madhya Pradesh     Indore
5  B-25967 2018-01-21       Sudevi   Uttar Pradesh  Prayagraj
6  B-25955 2018-01-16        Shiva     Maharashtra       Pune
7  B-26093 2018-03-27       Sarita     Maharashtra       Pune
8  B-25798 2018-10-01       Shishu  Andhra Pradesh  Hyderabad
9  B-25602 2018-04-01       Vrinda     Maharashtra       Pune

### Conversion rate (us dollar to rupee)

In [12]:
conversion_df = pd.read_csv('USDINRX.csv')
conversion_df.head(10)

         Date       Open       High        Low      Close  Adj Close  Volume
0  2003-12-01  45.709000  45.728001  45.615002  45.709999  45.709999     0.0
1  2003-12-02  45.709000  45.719002  45.560001  45.629002  45.629002     0.0
2  2003-12-03  45.632000  45.655998  45.474998  45.549999  45.549999     0.0
3  2003-12-04  45.548000  45.612999  45.519001  45.548000  45.548000     0.0
4  2003-12-05  45.549999  45.566002  45.449001  45.449001  45.449001     0.0
5  2003-12-08  45.474998  45.498001  45.395000  45.470001  45.470001     0.0
6  2003-12-09  45.471001  45.480000  45.403000  45.431000  45.431000     0.0
7  2003-12-10  45.419998  45.507999  45.354000  45.370998  45.370998     0.0
8  2003-12-11  45.373001  45.484001  45.352001  45.449001  45.449001     0.0
9  2003-12-12  45.448002  45.480000  45.421001  45.422001  45.422001     0.0

In [13]:
conversion_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4650 non-null   object
 1   Open       4598 non-null   float64
 2   High       4598 non-null   float64
 3   Low        4598 non-null   float64
 4   Close      4598 non-null   float64
 5   Adj Close  4598 non-null   float64
 6   Volume     4598 non-null   float64
dtypes: float64(6), object(1)
memory usage: 254.4+ KB

In [14]:
conversion_df['Date'] = pd.to_datetime(conversion_df['Date'])
conversion_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4650 non-null   datetime64[ns]
 1   Open       4598 non-null   float64
 2   High       4598 non-null   float64
 3   Low        4598 non-null   float64
 4   Close      4598 non-null   float64
 5   Adj Close  4598 non-null   float64
 6   Volume     4598 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 254.4 KB

In [15]:
# Select conversion rate in 2018
conversion_df = conversion_df[conversion_df['Date'].dt.year == 2018]
conversion_df.head(10)

           Date       Open       High        Low      Close  Adj Close  Volume
3675 2018-01-01  63.840801  63.869999  63.660000  63.840801  63.840801     0.0
3676 2018-01-02  63.867599  63.867599  63.419998  63.867599  63.867599     0.0
3677 2018-01-03  63.380001  63.580002  63.380001  63.459999  63.459999     0.0
3678 2018-01-04  63.419102  63.590000  63.330002  63.419102  63.419102     0.0
3679 2018-01-05  63.369598  63.419998  63.209999  63.369598  63.369598     0.0
3680 2018-01-08  63.264999  63.529999  63.230000  63.264999  63.264999     0.0
3681 2018-01-09  63.451801  63.730000  63.419998  63.452000  63.452000     0.0
3682 2018-01-10  63.635601  63.840000  63.568001  63.636101  63.636101     0.0
3683 2018-01-11  63.759998  63.840000  63.634998  63.759998  63.759998     0.0
3684 2018-01-12  63.672100  63.720001  63.478001  63.672100  63.672100     0.0

In [16]:
# Change usd to inr >> inr to usd
def inr_to_usd(open, close):
  return 1 / ((open + close) / 2 )

In [17]:
conversion_df['INR to USD'] = conversion_df.apply(lambda row: inr_to_usd(row['Open'], row['Close']), axis=1)
conversion_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,INR to USD
3675,2018-01-01,63.840801,63.869999,63.660000,63.840801,63.840801,0.0,0.015664
3676,2018-01-02,63.867599,63.867599,63.419998,63.867599,63.867599,0.0,0.015657
3677,2018-01-03,63.380001,63.580002,63.380001,63.459999,63.459999,0.0,0.015768
3678,2018-01-04,63.419102,63.590000,63.330002,63.419102,63.419102,0.0,0.015768
3679,2018-01-05,63.369598,63.419998,63.209999,63.369598,63.369598,0.0,0.015780
3680,2018-01-08,63.264999,63.529999,63.230000,63.264999,63.264999,0.0,0.015807
3681,2018-01-09,63.451801,63.730000,63.419998,63.452000,63.452000,0.0,0.015760
3682,2018-01-10,63.635601,63.840000,63.568001,63.636101,63.636101,0.0,0.015714
3683,2018-01-11,63.759998,63.840000,63.634998,63.759998,63.759998,0.0,0.015684
3684,2018-01-12,63.672100,63.720001,63.478001,63.672100,63.672100,0.0,0.015705

In [18]:
# Drop column
conversion_df = conversion_df.drop(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], axis=1)
conversion_df.head(10)

           Date  INR to USD
3675 2018-01-01    0.015664
3676 2018-01-02    0.015657
3677 2018-01-03    0.015768
3678 2018-01-04    0.015768
3679 2018-01-05    0.015780
3680 2018-01-08    0.015807
3681 2018-01-09    0.015760
3682 2018-01-10    0.015714
3683 2018-01-11    0.015684
3684 2018-01-12    0.015705

In [19]:
# Check missing value พบว่า มีข้อมูลอยู่ 261 เเถวแปลว่า มีข้อมูลอยู่ 261 วัน ไม่ครบ 365 วัน
conversion_df.isnull().count()

Date          261
INR to USD    261
dtype: int64

In [20]:
# เพิ่มข้อมูลเข้ามาโดย วันที่ไม่มีข้อมูลให้ใช้ข้อมูลของวันก่อนหน้า
import numpy as np
from datetime import datetime, timedelta

# สร้าง date range สำหรับทั้งปี 2018
full_date_range = pd.date_range(start='2018-01-01', end='2018-12-31', freq='D')
full_date_range

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25',
               '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29',
               '2018-12-30', '2018-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [21]:
# สร้าง DataFrame ใหม่ที่มีวันที่ครบทุกวัน
conversions_df_complete = pd.DataFrame({'date': full_date_range})
conversions_df_complete.head(10)

        date
0 2018-01-01
1 2018-01-02
2 2018-01-03
3 2018-01-04
4 2018-01-05
5 2018-01-06
6 2018-01-07
7 2018-01-08
8 2018-01-09
9 2018-01-10

In [22]:
# Merge กับข้อมูลเดิม
conversions_rate = conversions_df_complete.merge(conversion_df, how='left', left_on='date', right_on='Date')
conversions_rate.head(10)

        date       Date  INR to USD
0 2018-01-01 2018-01-01    0.015664
1 2018-01-02 2018-01-02    0.015657
2 2018-01-03 2018-01-03    0.015768
3 2018-01-04 2018-01-04    0.015768
4 2018-01-05 2018-01-05    0.015780
5 2018-01-06        NaT         NaN
6 2018-01-07        NaT         NaN
7 2018-01-08 2018-01-08    0.015807
8 2018-01-09 2018-01-09    0.015760
9 2018-01-10 2018-01-10    0.015714

In [23]:
# ใช้ forward fill เพื่อเติมค่าที่ว่างด้วยค่าก่อนหน้า
conversions_rate['INR to USD'] = conversions_rate['INR to USD'].ffill()
conversions_rate.head(10)

        date       Date  INR to USD
0 2018-01-01 2018-01-01    0.015664
1 2018-01-02 2018-01-02    0.015657
2 2018-01-03 2018-01-03    0.015768
3 2018-01-04 2018-01-04    0.015768
4 2018-01-05 2018-01-05    0.015780
5 2018-01-06        NaT    0.015780
6 2018-01-07        NaT    0.015780
7 2018-01-08 2018-01-08    0.015807
8 2018-01-09 2018-01-09    0.015760
9 2018-01-10 2018-01-10    0.015714

In [24]:
conversions_rate = conversions_rate.drop(['Date'], axis=1)
conversions_rate.head(10)

        date  INR to USD
0 2018-01-01    0.015664
1 2018-01-02    0.015657
2 2018-01-03    0.015768
3 2018-01-04    0.015768
4 2018-01-05    0.015780
5 2018-01-06    0.015780
6 2018-01-07    0.015780
7 2018-01-08    0.015807
8 2018-01-09    0.015760
9 2018-01-10    0.015714

In [25]:
conversions_rate.isnull().count()

date          365
INR to USD    365
dtype: int64

## Merge Data

In [26]:
sales_df = transactions_df.merge(customer_df, how='left', left_on='Order ID', right_on='Order ID')

In [27]:
final_df = sales_df.merge(conversions_rate, how='left', left_on='Order Date', right_on='date')
final_df.head(10)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,date,INR to USD
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,2018-06-04,Bhawna,Madhya Pradesh,Indore,2018-06-04,0.014935
1,B-26055,5729,64,14,Furniture,Chairs,EMI,2018-03-10,Harivansh,Uttar Pradesh,Mathura,2018-03-10,0.015363
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,2018-01-16,Shiva,Maharashtra,Pune,2018-01-16,0.015743
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,2018-03-27,Sarita,Maharashtra,Pune,2018-03-27,0.015442
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,2018-04-01,Vrinda,Maharashtra,Pune,2018-04-01,0.015368
5,B-25881,2244,247,4,Clothing,Trousers,Credit Card,2018-11-25,Lalita,Uttar Pradesh,Mathura,2018-11-25,0.014117
6,B-25696,275,-275,4,Clothing,Saree,COD,2018-06-21,Noopur,Karnataka,Bangalore,2018-06-21,0.014662
7,B-25687,387,-213,5,Clothing,Saree,UPI,2018-06-11,Sanjna,Maharashtra,Mumbai,2018-06-11,0.014811
8,B-25643,50,-44,2,Clothing,Hankerchief,UPI,2018-04-29,Kirti,Jammu and Kashmir,Kashmir,2018-04-29,0.014959
9,B-25851,135,-54,5,Clothing,Kurti,COD,2018-11-06,Kushal,Nagaland,Kohima,2018-11-06,0.013725

In [28]:
def usd_amount(amount, inr_to_usd):
  return amount * inr_to_usd

def usd_profit(profit, inr_to_usd):
  return profit * inr_to_usd

def total_amount(amount, quantity):
  return amount * quantity

def total_profit(profit, quantity):
  return profit * quantity

In [29]:
final_df['USD_Amount'] = final_df.apply(lambda row: usd_amount(row['Amount'], row['INR to USD']), axis=1)
final_df['USD_Profit'] = final_df.apply(lambda row: usd_profit(row['Profit'], row['INR to USD']), axis=1)
final_df['Total_Amount'] = final_df.apply(lambda row: total_amount(row['USD_Amount'], row['Quantity']), axis=1)
final_df['Total_Profit'] = final_df.apply(lambda row: total_profit(row['USD_Profit'], row['Quantity']), axis=1)
final_df.head(10)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,date,INR to USD,USD_Amount,USD_Profit,Total_Amount,Total_Profit
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,2018-06-04,Bhawna,Madhya Pradesh,Indore,2018-06-04,0.014935,16.368836,9.827276,114.581854,68.790930
1,B-26055,5729,64,14,Furniture,Chairs,EMI,2018-03-10,Harivansh,Uttar Pradesh,Mathura,2018-03-10,0.015363,88.016117,0.983249,1232.225639,13.765481
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,2018-01-16,Shiva,Maharashtra,Pune,2018-01-16,0.015743,46.078742,2.298427,368.629933,18.387417
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,2018-03-27,Sarita,Maharashtra,Pune,2018-03-27,0.015442,43.964698,10.995035,351.717585,87.960281
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,2018-04-01,Vrinda,Maharashtra,Pune,2018-04-01,0.015368,40.218844,17.688915,160.875377,70.755659
5,B-25881,2244,247,4,Clothing,Trousers,Credit Card,2018-11-25,Lalita,Uttar Pradesh,Mathura,2018-11-25,0.014117,31.679255,3.486977,126.717020,13.947907
6,B-25696,275,-275,4,Clothing,Saree,COD,2018-06-21,Noopur,Karnataka,Bangalore,2018-06-21,0.014662,4.032169,-4.032169,16.128678,-16.128678
7,B-25687,387,-213,5,Clothing,Saree,UPI,2018-06-11,Sanjna,Maharashtra,Mumbai,2018-06-11,0.014811,5.732038,-3.154843,28.660191,-15.774214
8,B-25643,50,-44,2,Clothing,Hankerchief,UPI,2018-04-29,Kirti,Jammu and Kashmir,Kashmir,2018-04-29,0.014959,0.747954,-0.658200,1.495909,-1.316400
9,B-25851,135,-54,5,Clothing,Kurti,COD,2018-11-06,Kushal,Nagaland,Kohima,2018-11-06,0.013725,1.852868,-0.741147,9.264342,-3.705737

In [30]:
final_df.columns

Index(['Order ID', 'Amount', 'Profit', 'Quantity', 'Category', 'Sub-Category',
       'PaymentMode', 'Order Date', 'CustomerName', 'State', 'City', 'date',
       'INR to USD', 'USD_Amount', 'USD_Profit', 'Total_Amount',
       'Total_Profit'],
      dtype='object')

In [31]:
final_dt = final_df.drop(['INR to USD', 'Amount', 'Profit', 'date'], axis=1)
final_dt.head(10)

,Order ID,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,USD_Amount,USD_Profit,Total_Amount,Total_Profit
0,B-25681,7,Electronics,Electronic Games,COD,2018-06-04,Bhawna,Madhya Pradesh,Indore,16.368836,9.827276,114.581854,68.790930
1,B-26055,14,Furniture,Chairs,EMI,2018-03-10,Harivansh,Uttar Pradesh,Mathura,88.016117,0.983249,1232.225639,13.765481
2,B-25955,8,Furniture,Bookcases,EMI,2018-01-16,Shiva,Maharashtra,Pune,46.078742,2.298427,368.629933,18.387417
3,B-26093,8,Electronics,Printers,Credit Card,2018-03-27,Sarita,Maharashtra,Pune,43.964698,10.995035,351.717585,87.960281
4,B-25602,4,Electronics,Phones,Credit Card,2018-04-01,Vrinda,Maharashtra,Pune,40.218844,17.688915,160.875377,70.755659
5,B-25881,4,Clothing,Trousers,Credit Card,2018-11-25,Lalita,Uttar Pradesh,Mathura,31.679255,3.486977,126.717020,13.947907
6,B-25696,4,Clothing,Saree,COD,2018-06-21,Noopur,Karnataka,Bangalore,4.032169,-4.032169,16.128678,-16.128678
7,B-25687,5,Clothing,Saree,UPI,2018-06-11,Sanjna,Maharashtra,Mumbai,5.732038,-3.154843,28.660191,-15.774214
8,B-25643,2,Clothing,Hankerchief,UPI,2018-04-29,Kirti,Jammu and Kashmir,Kashmir,0.747954,-0.658200,1.495909,-1.316400
9,B-25851,5,Clothing,Kurti,COD,2018-11-06,Kushal,Nagaland,Kohima,1.852868,-0.741147,9.264342,-3.705737

In [32]:
final_dt = final_dt.rename(columns={'Sub-Category': 'Sub Category'})

In [33]:
final_dt.columns.tolist()

['Order ID',
 'Quantity',
 'Category',
 'Sub Category',
 'PaymentMode',
 'Order Date',
 'CustomerName',
 'State',
 'City',
 'USD_Amount',
 'USD_Profit',
 'Total_Amount',
 'Total_Profit']

In [34]:
final_dt = final_dt[['Order ID', 'Order Date', 'USD_Amount', 'USD_Profit', 'Quantity', 'Total_Amount', 'Total_Profit','Category', 'Sub Category','PaymentMode', 'CustomerName', 'State', 'City' ]]
final_dt.head(10)

,Order ID,Order Date,USD_Amount,USD_Profit,Quantity,Total_Amount,Total_Profit,Category,Sub Category,PaymentMode,CustomerName,State,City
0,B-25681,2018-06-04,16.368836,9.827276,7,114.581854,68.790930,Electronics,Electronic Games,COD,Bhawna,Madhya Pradesh,Indore
1,B-26055,2018-03-10,88.016117,0.983249,14,1232.225639,13.765481,Furniture,Chairs,EMI,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2018-01-16,46.078742,2.298427,8,368.629933,18.387417,Furniture,Bookcases,EMI,Shiva,Maharashtra,Pune
3,B-26093,2018-03-27,43.964698,10.995035,8,351.717585,87.960281,Electronics,Printers,Credit Card,Sarita,Maharashtra,Pune
4,B-25602,2018-04-01,40.218844,17.688915,4,160.875377,70.755659,Electronics,Phones,Credit Card,Vrinda,Maharashtra,Pune
5,B-25881,2018-11-25,31.679255,3.486977,4,126.717020,13.947907,Clothing,Trousers,Credit Card,Lalita,Uttar Pradesh,Mathura
6,B-25696,2018-06-21,4.032169,-4.032169,4,16.128678,-16.128678,Clothing,Saree,COD,Noopur,Karnataka,Bangalore
7,B-25687,2018-06-11,5.732038,-3.154843,5,28.660191,-15.774214,Clothing,Saree,UPI,Sanjna,Maharashtra,Mumbai
8,B-25643,2018-04-29,0.747954,-0.658200,2,1.495909,-1.316400,Clothing,Hankerchief,UPI,Kirti,Jammu and Kashmir,Kashmir
9,B-25851,2018-11-06,1.852868,-0.741147,5,9.264342,-3.705737,Clothing,Kurti,COD,Kushal,Nagaland,Kohima

In [35]:
final_dt['Order Date'] = pd.to_datetime(final_dt['Order Date'], format='%Y-%m-%d')
final_dt.head(10)

,Order ID,Order Date,USD_Amount,USD_Profit,Quantity,Total_Amount,Total_Profit,Category,Sub Category,PaymentMode,CustomerName,State,City
0,B-25681,2018-06-04,16.368836,9.827276,7,114.581854,68.790930,Electronics,Electronic Games,COD,Bhawna,Madhya Pradesh,Indore
1,B-26055,2018-03-10,88.016117,0.983249,14,1232.225639,13.765481,Furniture,Chairs,EMI,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2018-01-16,46.078742,2.298427,8,368.629933,18.387417,Furniture,Bookcases,EMI,Shiva,Maharashtra,Pune
3,B-26093,2018-03-27,43.964698,10.995035,8,351.717585,87.960281,Electronics,Printers,Credit Card,Sarita,Maharashtra,Pune
4,B-25602,2018-04-01,40.218844,17.688915,4,160.875377,70.755659,Electronics,Phones,Credit Card,Vrinda,Maharashtra,Pune
5,B-25881,2018-11-25,31.679255,3.486977,4,126.717020,13.947907,Clothing,Trousers,Credit Card,Lalita,Uttar Pradesh,Mathura
6,B-25696,2018-06-21,4.032169,-4.032169,4,16.128678,-16.128678,Clothing,Saree,COD,Noopur,Karnataka,Bangalore
7,B-25687,2018-06-11,5.732038,-3.154843,5,28.660191,-15.774214,Clothing,Saree,UPI,Sanjna,Maharashtra,Mumbai
8,B-25643,2018-04-29,0.747954,-0.658200,2,1.495909,-1.316400,Clothing,Hankerchief,UPI,Kirti,Jammu and Kashmir,Kashmir
9,B-25851,2018-11-06,1.852868,-0.741147,5,9.264342,-3.705737,Clothing,Kurti,COD,Kushal,Nagaland,Kohima

In [36]:
final_dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Order Date    1500 non-null   datetime64[ns]
 2   USD_Amount    1500 non-null   float64
 3   USD_Profit    1500 non-null   float64
 4   Quantity      1500 non-null   int64
 5   Total_Amount  1500 non-null   float64
 6   Total_Profit  1500 non-null   float64
 7   Category      1500 non-null   object
 8   Sub Category  1500 non-null   object
 9   PaymentMode   1500 non-null   object
 10  CustomerName  1500 non-null   object
 11  State         1500 non-null   object
 12  City          1500 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 152.5+ KB

In [37]:
final_dt.columns = final_dt.columns.str.lower().str.replace(' ', '_')
final_dt.head(10)

,order_id,order_date,usd_amount,usd_profit,quantity,total_amount,total_profit,category,sub_category,paymentmode,customername,state,city
0,B-25681,2018-06-04,16.368836,9.827276,7,114.581854,68.790930,Electronics,Electronic Games,COD,Bhawna,Madhya Pradesh,Indore
1,B-26055,2018-03-10,88.016117,0.983249,14,1232.225639,13.765481,Furniture,Chairs,EMI,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2018-01-16,46.078742,2.298427,8,368.629933,18.387417,Furniture,Bookcases,EMI,Shiva,Maharashtra,Pune
3,B-26093,2018-03-27,43.964698,10.995035,8,351.717585,87.960281,Electronics,Printers,Credit Card,Sarita,Maharashtra,Pune
4,B-25602,2018-04-01,40.218844,17.688915,4,160.875377,70.755659,Electronics,Phones,Credit Card,Vrinda,Maharashtra,Pune
5,B-25881,2018-11-25,31.679255,3.486977,4,126.717020,13.947907,Clothing,Trousers,Credit Card,Lalita,Uttar Pradesh,Mathura
6,B-25696,2018-06-21,4.032169,-4.032169,4,16.128678,-16.128678,Clothing,Saree,COD,Noopur,Karnataka,Bangalore
7,B-25687,2018-06-11,5.732038,-3.154843,5,28.660191,-15.774214,Clothing,Saree,UPI,Sanjna,Maharashtra,Mumbai
8,B-25643,2018-04-29,0.747954,-0.658200,2,1.495909,-1.316400,Clothing,Hankerchief,UPI,Kirti,Jammu and Kashmir,Kashmir
9,B-25851,2018-11-06,1.852868,-0.741147,5,9.264342,-3.705737,Clothing,Kurti,COD,Kushal,Nagaland,Kohima

In [38]:
final_dt.isnull().count()

order_id        1500
order_date      1500
usd_amount      1500
usd_profit      1500
quantity        1500
total_amount    1500
total_profit    1500
category        1500
sub_category    1500
paymentmode     1500
customername    1500
state           1500
city            1500
dtype: int64

## Export to parquet

In [39]:
import pyarrow as pa
final_dt.to_parquet('online_sales_dt.parquet', engine='pyarrow', index= False)

In [40]:
final_check = pd.read_parquet('online_sales_dt.parquet')
final_check.head(10)

,order_id,order_date,usd_amount,usd_profit,quantity,total_amount,total_profit,category,sub_category,paymentmode,customername,state,city
0,B-25681,2018-06-04,16.368836,9.827276,7,114.581854,68.790930,Electronics,Electronic Games,COD,Bhawna,Madhya Pradesh,Indore
1,B-26055,2018-03-10,88.016117,0.983249,14,1232.225639,13.765481,Furniture,Chairs,EMI,Harivansh,Uttar Pradesh,Mathura
2,B-25955,2018-01-16,46.078742,2.298427,8,368.629933,18.387417,Furniture,Bookcases,EMI,Shiva,Maharashtra,Pune
3,B-26093,2018-03-27,43.964698,10.995035,8,351.717585,87.960281,Electronics,Printers,Credit Card,Sarita,Maharashtra,Pune
4,B-25602,2018-04-01,40.218844,17.688915,4,160.875377,70.755659,Electronics,Phones,Credit Card,Vrinda,Maharashtra,Pune
5,B-25881,2018-11-25,31.679255,3.486977,4,126.717020,13.947907,Clothing,Trousers,Credit Card,Lalita,Uttar Pradesh,Mathura
6,B-25696,2018-06-21,4.032169,-4.032169,4,16.128678,-16.128678,Clothing,Saree,COD,Noopur,Karnataka,Bangalore
7,B-25687,2018-06-11,5.732038,-3.154843,5,28.660191,-15.774214,Clothing,Saree,UPI,Sanjna,Maharashtra,Mumbai
8,B-25643,2018-04-29,0.747954,-0.658200,2,1.495909,-1.316400,Clothing,Hankerchief,UPI,Kirti,Jammu and Kashmir,Kashmir
9,B-25851,2018-11-06,1.852868,-0.741147,5,9.264342,-3.705737,Clothing,Kurti,COD,Kushal,Nagaland,Kohima

In [41]:
final_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      1500 non-null   object
 1   order_date    1500 non-null   datetime64[ns]
 2   usd_amount    1500 non-null   float64
 3   usd_profit    1500 non-null   float64
 4   quantity      1500 non-null   int64
 5   total_amount  1500 non-null   float64
 6   total_profit  1500 non-null   float64
 7   category      1500 non-null   object
 8   sub_category  1500 non-null   object
 9   paymentmode   1500 non-null   object
 10  customername  1500 non-null   object
 11  state         1500 non-null   object
 12  city          1500 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 152.5+ KB

In [42]:
final_check.columns.tolist()

['order_id',
 'order_date',
 'usd_amount',
 'usd_profit',
 'quantity',
 'total_amount',
 'total_profit',
 'category',
 'sub_category',
 'paymentmode',
 'customername',
 'state',
 'city']